tls:
  keystore:    
    keyPassword: "![KCyFyi9rvi0/bS4Jqd1XG9SoyjmF9Kcx]" 
    password: "![KCyFyi9rvi0/bS4Jqd1XG9SoyjmF9Kcx]"

activeMQConsumer:
  password: "![TMS4M6Upz20=]"
  
anypointMQConsumer:
  covid19CaseDistributionQueue:
    clientAppId: ""
    clientSecret: ""
  usCountiesCovid19CaseQueue:
    clientAppId: ""
    clientSecret: ""