http:
  port: "8083"
  private:
    port: "8091"
    
https:
  port: "8082"
  private:
    port: "8092"
    
api:
  id: "18350167"
  majorVersion: "v1"
  groupId: "62123581-121b-4c73-bf9d-19d53054fb8e"
  artifactId: "covid19-case-data-papi"
  version: "1.0.1"
  specification: "resource::${api.groupId}:${api.artifactId}:${api.version}:raml:zip:covid19-case-data-papi.raml"

databaseSapi:
  host: "localhost"
  port: "8085"
  basePath: "/api"
  caseDistributionData:    
    path: "/covid19CaseData"
    untilSuccessfull:
      maxRetries: "3"
      timeInterval: "30000"
  usCountiesCovid19Data:  
    path: "/usCountiesCovid19CaseData"
    untilSuccessfull:
      maxRetries: "3"
      timeInterval: "30000"

##Trigger Case Distribution SAPI    
caseDistributionSapi:
  host: "localhost"
  port: "8084"
  basePath: "/api"      
  path: "/covid19CaseDistribution"
  untilSuccessfull:
      maxRetries: "3"
      timeInterval: "30000"
      
##Trigger US Counties Covid19 Case SAPI    
usCountiesSapi:
  host: "localhost"
  port: "8086"
  basePath: "/api"      
  path: "/usCountiesCovid19Case"
  untilSuccessfull:
      maxRetries: "3"
      timeInterval: "30000"
      
activeMQConsumer:
   username: "admin"
   brokerUrl: "tcp://192.168.8.126:61616?jms.prefetchPolicy.queuePrefetch=10"   
   caseDistributionQueue:  
    name: "Covid19CaseDistributionQueue"
    reconnection:
      maxAttempt: "3"
      frequency: "30000"
   usCountiesQueue:
    name: "USCountiesCovid19CaseQueue"
    reconnection:
      maxAttempt: "3"
      frequency: "30000"
    
//anypointMQConsumer:  
  //url: "https://mq-us-east-1.anypoint.mulesoft.com/api/v1"
  //covid19CaseDistributionQueue:
    //clientAppId: ""
    //clientSecret: ""
    //name: "Covid19CaseDistributionQueue"
  //usCountiesCovid19CaseQueue:
    //clientAppId: ""
    //clientSecret: ""
    //name: "USCountiesCovid19CaseQueue"